name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            artifact_name: reedy
            asset_name: reedy-linux
          - os: macos-latest
            artifact_name: reedy
            asset_name: reedy-macos
          - os: windows-latest
            artifact_name: reedy.exe
            asset_name: reedy-windows.exe

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history and tags
      
      - name: Check if on main branch
        id: check_branch
        run: |
          # Get the branch that the tag is on
          TAG_BRANCH=$(git branch -r --contains ${{ github.ref }} | grep -v "HEAD" | head -n 1 | xargs)
          echo "Tag is on branch: $TAG_BRANCH"
          
          # Only proceed if the tag is on main
          if [[ "$TAG_BRANCH" == *"main" ]]; then
            echo "tag_on_main=true" >> $GITHUB_OUTPUT
          else
            echo "tag_on_main=false" >> $GITHUB_OUTPUT
            echo "Tag is not on main branch, skipping release"
          fi

      - name: Setup Rust
        if: steps.check_branch.outputs.tag_on_main == 'true'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        if: steps.check_branch.outputs.tag_on_main == 'true'
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Upload binaries to release
        if: steps.check_branch.outputs.tag_on_main == 'true'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
          overwrite: true